= Connect API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2

== 로그인

operation::oauth-controller-test/이미_존재하는_사용자[snippets="http-request,request-headers,response-headers"]

=== 이미 존재하는 사용자

operation::oauth-controller-test/이미_존재하는_사용자[snippets="http-request,http-response"]

=== 존재하지 않는 사용자

operation::oauth-controller-test/존재하지_않는_사용자[snippets="http-request,http-response"]

=== 잘못된 이메일

operation::oauth-controller-test/잘못된_이메일[snippets="http-request,http-response"]

== 실종

=== 실종 등록

operation::missing-controller-test/실종등록[snippets="request-headers,request-fields,http-request,http-response"]

=== 근처 실종 정보 가져오기

operation::missing-controller-test/근처_실종_정보_가져오기[snippets="query-parameters,response-fields,http-request,http-response"]

=== 자세한 실종 정보 가져오기

operation::missing-controller-test/자세한_실종_정보_가져오기[snippets="path-parameters,response-fields,http-request,http-response"]

== 제보

=== 실종 되어있는 애완동물의 제보 등록

operation::report-controller-test/제보_등록_실종등록[snippets="request-headers,request-parts,request-part-reportCreateRequestDTO-fields,http-request,http-response"]

=== 임의의 애완동물 제보 등록

operation::report-controller-test/제보_등록_임의제보[snippets="request-headers,request-parts,request-part-reportCreateRequestDTO-fields,http-request,http-response"]

=== 받은 제보 확인

operation::report-controller-test/받은_제보_확인[snippets="request-headers,response-fields,http-request,http-response"]

=== 위치 경도 기반 지역의 실종 제보 확인

operation::report-controller-test/지역의_실종_제보_확인[snippets="query-parameters,response-fields,http-request,http-response"]

=== 제보의 상제 정보 가져오기

operation::report-controller-test/제보_상세_정보_확인[snippets="path-parameters,http-request,http-response"]

== 등록

=== 사용자와 펫 정보 등록

operation::register-controller-test/사용자와_펫_정보_등록[snippets="request-headers,request-parts,request-part-PetRegisterDTO-fields,http-request,http-response"]